# Site settings
title: sam forderer 
email: samforderer@icloud.com 
description: > # this means to ignore newlines until "baseurl:"
  Sam Forderer | dev | design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
sass: 
  sass_dir: _sass
  style: compressed
