# Site settings
title: ALBION 
email: samforderer@icloud.com 
description: > # this means to ignore newlines until "baseurl:"
  ALBION web dev & design
   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://al-bi-on.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass: 
  sass_dir: _sass
  style: compressed
